import 'package:app/util/model/selectedPlace.dart';
import 'package:app/util/model/subPlaces.dart';

class Saipan {
  static List<Category> getMockCategories() {
    return [
      Category(
          name: "Places",
          imageUrl: "assets/images/Places/managaha.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: 'Places',
                name: 'Managaha Island',
                imageUrl: 'assets/images/Places/managaha.jpg',
                location: 'Saipan',
                description: "",
                distance: 25,
                rating: 5,
                subPlaces: []),
            subPlaces(
                activityType: 'Places',
                name: 'Banzai Cliff',
                imageUrl: 'assets/images/Places/banzai.jpg',
                location: 'Saipan',
                description: "",
                distance: 25,
                rating: 5,
                subPlaces: []),
          ]),
      Category(
          name: "Activities",
          imageUrl: "assets/images/Activities/kaiyak.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: "Activities",
                name: "Kayak",
                imageUrl: 'assets/images/Activities/kaiyak.jpg',
                location: 'Saipan',
                description: "",
                distance: 24,
                rating: 2,
                subPlaces: []),
          ]),
      Category(
          name: "Restaurants",
          imageUrl: "assets/images/Restaurants/restaurant.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: "Restaurants",
                name: 'The Shack Saipan',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Revolving Restaurant 360',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Himawari',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: ' Country House Restaurant',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Shirley's Coffee Shop",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Spicy Thai Noodle Place',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Godfather's Bar",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Spicy Thai Noodle Place',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Giovanni's",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 5,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Loco & Taco Smoke Dining Bar',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Naked Fish Bar & Grill',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
          ]),
    ];
  }
}

class Tinian {
  static List<Category> getMockCategories() {
    return [
      Category(
          name: "Restaurants",
          imageUrl: "assets/images/Restaurants/restaurant.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: "Restaurants",
                name: 'The Shack Saipan',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Revolving Restaurant 360',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Himawari',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: ' Country House Restaurant',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Shirley's Coffee Shop",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Spicy Thai Noodle Place',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Godfather's Bar",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Spicy Thai Noodle Place',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Giovanni's",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 5,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Loco & Taco Smoke Dining Bar',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Naked Fish Bar & Grill',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
          ]),
      Category(
          name: "Places",
          imageUrl: "assets/images/Places/managaha.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: 'Places',
                name: 'Managaha Island',
                imageUrl: 'assets/images/Places/managaha.jpg',
                location: 'Saipan',
                description: "",
                distance: 25,
                rating: 5,
                subPlaces: []),
            subPlaces(
                activityType: 'Places',
                name: 'Banzai Cliff',
                imageUrl: 'assets/images/Places/banzai.jpg',
                location: 'Saipan',
                description: "",
                distance: 25,
                rating: 5,
                subPlaces: []),
          ]),
      Category(
          name: "Activities",
          imageUrl: "assets/images/Activities/kaiyak.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: "Activities",
                name: "Kayak",
                imageUrl: 'assets/images/Activities/kaiyak.jpg',
                location: 'Saipan',
                description: "",
                distance: 24,
                rating: 2,
                subPlaces: []),
          ]),
    ];
  }
}

class Rota {
  static List<Category> getMockCategories() {
    return [
      Category(
          name: "Restaurants",
          imageUrl: "assets/images/Restaurants/restaurant.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: "Restaurants",
                name: 'The Shack Saipan',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Revolving Restaurant 360',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Himawari',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: ' Country House Restaurant',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Shirley's Coffee Shop",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Spicy Thai Noodle Place',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Godfather's Bar",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Spicy Thai Noodle Place',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: "Giovanni's",
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 5,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Loco & Taco Smoke Dining Bar',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
            subPlaces(
                activityType: "Restaurants",
                name: 'Naked Fish Bar & Grill',
                imageUrl: 'assets/images/Restaurants/countryhouse.jpg',
                location: 'Saipan',
                description: "",
                distance: 2,
                rating: 4,
                subPlaces: []),
          ]),
      Category(
          name: "Places",
          imageUrl: "assets/images/Places/managaha.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: 'Places',
                name: 'Managaha Island',
                imageUrl: 'assets/images/Places/managaha.jpg',
                location: 'Saipan',
                description: "",
                distance: 25,
                rating: 5,
                subPlaces: []),
            subPlaces(
                activityType: 'Places',
                name: 'Banzai Cliff',
                imageUrl: 'assets/images/Places/banzai.jpg',
                location: 'Saipan',
                description: "",
                distance: 25,
                rating: 5,
                subPlaces: []),
          ]),
      Category(
          name: "Activities",
          imageUrl: "assets/images/Activities/kaiyak.jpg",
          location: "Saipan",
          description: "Good Place",
          distance: 2,
          rating: 2,
          subPlaces: [
            subPlaces(
                activityType: "Activities",
                name: "Kayak",
                imageUrl: 'assets/images/Activities/kaiyak.jpg',
                location: 'Saipan',
                description: "",
                distance: 24,
                rating: 2,
                subPlaces: []),
          ]),
    ];
  }
}
